"""Generate the deliverables from the library and the notes.

Everything here is mechanical — derived entirely from papers/library.jsonl and
papers/notes/*.md. Nothing in these outputs is written from memory, which is
what makes them checkable. The one hand-written document, review/synthesis.md,
is left alone by this script.

    python3 scripts/report.py                 # all outputs
    python3 scripts/report.py --stubs         # create missing note templates
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from pathlib import Path

from common import LIBRARY, NOTES_DIR, ROOT, Store, assign_citekeys, log, venue_tier
from notes import SECTIONS, note_path, parse_note, summarize, template
from topic import categorize

REVIEW_DIR = ROOT / "review"

BIB_PATH = REVIEW_DIR / "annotated-bibliography.md"
TABLE_PATH = REVIEW_DIR / "comparison-table.md"
BIBTEX_PATH = REVIEW_DIR / "references.bib"


def included(store: Store) -> list[dict]:
    papers = store.by_status("included")
    papers.sort(key=lambda r: (
        -(r.get("priority") or 0),
        sorted(r.get("categories") or categorize(r)),
        -(r.get("cited_by_count") or 0),
    ))
    return papers


def author_line(rec: dict, limit: int = 4) -> str:
    authors = rec.get("authors") or []
    if not authors:
        return "Unknown"
    shown = ", ".join(authors[:limit])
    return shown + (" et al." if len(authors) > limit else "")


def venue_line(rec: dict) -> str:
    venue = rec.get("venue_short") or rec.get("venue") or "?"
    return f"{venue} {rec.get('year', '')}".strip()


def link_line(rec: dict) -> str:
    bits = []
    if rec.get("doi"):
        bits.append(f"[doi](https://doi.org/{rec['doi']})")
    if rec.get("arxiv_id"):
        bits.append(f"[arXiv](https://arxiv.org/abs/{rec['arxiv_id']})")
    if rec.get("pdf_url"):
        bits.append(f"[pdf]({rec['pdf_url']})")
    return " · ".join(bits)


# --------------------------------------------------------------------------
# stubs
# --------------------------------------------------------------------------

def write_stubs(store: Store) -> int:
    """Create a blank note for every included paper that lacks one."""
    NOTES_DIR.mkdir(parents=True, exist_ok=True)
    created = 0
    for rec in included(store):
        path = note_path(rec["citekey"])
        if not path.exists():
            path.write_text(template(rec), encoding="utf-8")
            rec["note_path"] = str(path.relative_to(ROOT))
            created += 1
    store.save()
    return created


# --------------------------------------------------------------------------
# annotated bibliography
# --------------------------------------------------------------------------

def build_bibliography(store: Store) -> str:
    papers = included(store)
    by_category: dict[str, list[dict]] = defaultdict(list)
    for rec in papers:
        for cat in (rec.get("categories") or categorize(rec)) or ["uncategorized"]:
            by_category[cat].append(rec)

    out = [
        "# Annotated bibliography",
        "",
        f"{len(papers)} included papers. Generated by `scripts/report.py` — "
        "edit the notes in `papers/notes/`, not this file.",
        "",
        "## Contents",
        "",
    ]
    for cat in sorted(by_category):
        out.append(f"- [{cat}](#{cat}) — {len(by_category[cat])}")
    out.append("")

    for cat in sorted(by_category):
        out += [f"## {cat}", ""]
        for rec in by_category[cat]:
            sections = {}
            path = note_path(rec.get("citekey", ""))
            if path.exists():
                sections = parse_note(path)

            out += [
                f"### {rec.get('title', 'Untitled')}",
                "",
                f"`{rec.get('citekey', '')}` · {author_line(rec)} · {venue_line(rec)}"
                + (f" · {rec['cited_by_count']} citations" if rec.get("cited_by_count") else ""),
                "",
            ]
            links = link_line(rec)
            if links:
                out += [links, ""]
            if rec.get("reason"):
                out += [f"**Why included:** {rec['reason']}", ""]

            if sections:
                for name in SECTIONS:
                    body = sections.get(name.lower(), "").strip()
                    if body:
                        out += [f"**{name}.** {body}", ""]
            else:
                out += ["_No note yet._", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------
# comparison table
# --------------------------------------------------------------------------

TABLE_COLUMNS = [
    ("Paper", lambda rec, sec: f"`{rec.get('citekey', '')}`"),
    ("Venue", lambda rec, sec: venue_line(rec)),
    ("Categories", lambda rec, sec: ", ".join(rec.get("categories") or categorize(rec))),
    ("Problem", lambda rec, sec: summarize(sec.get("problem", ""))),
    ("Main idea", lambda rec, sec: summarize(sec.get("main ideas", ""))),
    ("Evaluation", lambda rec, sec: summarize(sec.get("evaluation", ""))),
    ("Limitations", lambda rec, sec: summarize(sec.get("limitations", ""))),
]


def build_table(store: Store) -> str:
    papers = included(store)
    out = [
        "# Cross-paper comparison",
        "",
        f"{len(papers)} included papers, ordered by priority then category. "
        "Every cell is derived from `papers/notes/<citekey>.md`; a blank cell "
        "means the note has not been written yet.",
        "",
        "| " + " | ".join(name for name, _ in TABLE_COLUMNS) + " |",
        "|" + "|".join(["---"] * len(TABLE_COLUMNS)) + "|",
    ]
    for rec in papers:
        path = note_path(rec.get("citekey", ""))
        sections = parse_note(path) if path.exists() else {}
        cells = [render(rec, sections) for _, render in TABLE_COLUMNS]
        out.append("| " + " | ".join(cell or "—" for cell in cells) + " |")

    out += ["", "## Coverage", ""]
    cats = Counter(c for r in papers for c in (r.get("categories") or categorize(r)))
    venues = Counter(r.get("venue_short") or "other" for r in papers)
    years = Counter(r.get("year") for r in papers)
    tiers = Counter(venue_tier(r) for r in papers)

    out += ["| Category | Papers |", "|---|---|"]
    out += [f"| {cat} | {n} |" for cat, n in cats.most_common()]
    out += ["", "| Venue | Papers |", "|---|---|"]
    out += [f"| {venue} | {n} |" for venue, n in venues.most_common()]
    out += ["", "| Year | Papers |", "|---|---|"]
    out += [f"| {year} | {n} |" for year, n in sorted(years.items(), key=lambda kv: kv[0] or 0)]
    out += ["", f"Venue tier: {dict(tiers)}", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------
# bibtex
# --------------------------------------------------------------------------

def _bibtex_escape(value: str) -> str:
    return value.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def build_bibtex(store: Store) -> str:
    entries = []
    for rec in included(store):
        is_preprint = not rec.get("doi") or (rec.get("venue_short") == "arXiv")
        kind = "misc" if is_preprint else "inproceedings"
        fields = [
            ("title", _bibtex_escape(rec.get("title", ""))),
            ("author", _bibtex_escape(" and ".join(rec.get("authors") or []))),
            ("year", str(rec.get("year") or "")),
        ]
        if not is_preprint:
            fields.append(("booktitle", _bibtex_escape(rec.get("venue", ""))))
        if rec.get("doi"):
            fields.append(("doi", rec["doi"]))
        if rec.get("arxiv_id"):
            fields.append(("eprint", rec["arxiv_id"]))
            fields.append(("archivePrefix", "arXiv"))
        if rec.get("url"):
            fields.append(("url", rec["url"]))

        body = ",\n".join(f"  {k} = {{{v}}}" for k, v in fields if v)
        entries.append(f"@{kind}{{{rec['citekey']},\n{body}\n}}")
    header = (
        "% Generated by scripts/report.py from papers/library.jsonl.\n"
        "% Every entry corresponds to a record fetched from a live API.\n\n"
    )
    return header + "\n\n".join(entries) + "\n"


# --------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stubs", action="store_true",
                    help="also create blank notes for included papers that lack one")
    args = ap.parse_args()

    store = Store()
    assign_citekeys(store)
    store.save()

    REVIEW_DIR.mkdir(parents=True, exist_ok=True)
    if args.stubs:
        log(f"created {write_stubs(store)} note stubs")

    BIB_PATH.write_text(build_bibliography(store), encoding="utf-8")
    TABLE_PATH.write_text(build_table(store), encoding="utf-8")
    BIBTEX_PATH.write_text(build_bibtex(store), encoding="utf-8")

    papers = included(store)
    with_notes = sum(1 for r in papers if note_path(r.get("citekey", "")).exists())
    log(f"wrote {BIB_PATH.name}, {TABLE_PATH.name}, {BIBTEX_PATH.name}")
    log(f"{len(papers)} included papers, {with_notes} with notes")


if __name__ == "__main__":
    main()
